# Generated by Django 2.2.4 on 2019-11-09 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20191109_0217'),
        ('activities', '0006_auto_20191108_2058'),
    ]

    operations = [
    ]
